
import java.util.ArrayList;
import javax.swing.JFrame;

public class NewJFrame extends javax.swing.JFrame {

    private int type;

    public NewJFrame() {
        initComponents();
        visibleCC();
        visible6f();
        visible0F();
        type = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lb_01 = new javax.swing.JPanel();
        lb_0 = new javax.swing.JLabel();
        cc_1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lb_1 = new javax.swing.JLabel();
        lb_2 = new javax.swing.JLabel();
        lb_3 = new javax.swing.JLabel();
        lb_4 = new javax.swing.JLabel();
        lb_5 = new javax.swing.JLabel();
        lb_6 = new javax.swing.JLabel();
        cc_2 = new javax.swing.JComboBox<>();
        cc_0 = new javax.swing.JComboBox<>();
        cc_3 = new javax.swing.JComboBox<>();
        cc_4 = new javax.swing.JComboBox<>();
        cc_5 = new javax.swing.JComboBox<>();
        cc_6 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(61, 61, 61));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jButton1.setBackground(new java.awt.Color(61, 61, 61));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Modo Usuário");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(61, 61, 61));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Modo Kernel");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(61, 61, 61));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Threads ");

        lb_01.setBackground(new java.awt.Color(80, 83, 85));

        lb_0.setForeground(new java.awt.Color(255, 255, 255));
        lb_0.setText("Processos");

        cc_1.setBackground(new java.awt.Color(61, 61, 61));
        cc_1.setForeground(new java.awt.Color(255, 255, 255));
        cc_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Threads do processo");

        lb_1.setForeground(new java.awt.Color(255, 255, 255));
        lb_1.setText("1º");

        lb_2.setForeground(new java.awt.Color(255, 255, 255));
        lb_2.setText("2º");

        lb_3.setForeground(new java.awt.Color(255, 255, 255));
        lb_3.setText("3º");

        lb_4.setForeground(new java.awt.Color(255, 255, 255));
        lb_4.setText("4º");

        lb_5.setForeground(new java.awt.Color(255, 255, 255));
        lb_5.setText("5º");

        lb_6.setForeground(new java.awt.Color(255, 255, 255));
        lb_6.setText("Threads disponíveis");

        cc_2.setBackground(new java.awt.Color(61, 61, 61));
        cc_2.setForeground(new java.awt.Color(255, 255, 255));
        cc_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        cc_0.setBackground(new java.awt.Color(61, 61, 61));
        cc_0.setForeground(new java.awt.Color(255, 255, 255));
        cc_0.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        cc_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cc_0ActionPerformed(evt);
            }
        });

        cc_3.setBackground(new java.awt.Color(61, 61, 61));
        cc_3.setForeground(new java.awt.Color(255, 255, 255));
        cc_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        cc_4.setBackground(new java.awt.Color(61, 61, 61));
        cc_4.setForeground(new java.awt.Color(255, 255, 255));
        cc_4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        cc_5.setBackground(new java.awt.Color(61, 61, 61));
        cc_5.setForeground(new java.awt.Color(255, 255, 255));
        cc_5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        cc_6.setBackground(new java.awt.Color(61, 61, 61));
        cc_6.setForeground(new java.awt.Color(255, 255, 255));
        cc_6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jButton3.setBackground(new java.awt.Color(61, 61, 61));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-flecha-50.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lb_01Layout = new javax.swing.GroupLayout(lb_01);
        lb_01.setLayout(lb_01Layout);
        lb_01Layout.setHorizontalGroup(
            lb_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lb_01Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(lb_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lb_01Layout.createSequentialGroup()
                        .addComponent(lb_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cc_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lb_01Layout.createSequentialGroup()
                        .addComponent(lb_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cc_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lb_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cc_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lb_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cc_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lb_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cc_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lb_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cc_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(lb_01Layout.createSequentialGroup()
                        .addComponent(lb_0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cc_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lb_01Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(91, 91, 91))
        );
        lb_01Layout.setVerticalGroup(
            lb_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lb_01Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(lb_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_0)
                    .addComponent(cc_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lb_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_1)
                    .addComponent(lb_2)
                    .addComponent(lb_3)
                    .addComponent(lb_4)
                    .addComponent(lb_5)
                    .addComponent(cc_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cc_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cc_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cc_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cc_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(lb_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_6)
                    .addComponent(cc_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        visibleCC();
        visible6T();
        visible0T();
        type = 1;
    }//GEN-LAST:event_jButton2ActionPerformed
    private void visibleCC() {
        lb_1.setVisible(false);
        lb_2.setVisible(false);
        lb_3.setVisible(false);
        lb_4.setVisible(false);
        lb_5.setVisible(false);
        cc_1.setVisible(false);
        cc_2.setVisible(false);
        cc_3.setVisible(false);
        cc_4.setVisible(false);
        cc_5.setVisible(false);

    }

    private void setIndex() {
        cc_1.setSelectedIndex(0);
        cc_2.setSelectedIndex(0);
        cc_3.setSelectedIndex(0);
        cc_4.setSelectedIndex(0);
        cc_5.setSelectedIndex(0);
    }

    private void visible0T() {
        lb_0.setVisible(true);
        lb_01.setVisible(true);
        cc_0.setVisible(true);

    }

    private void visible0F() {
        lb_0.setVisible(false);
        lb_01.setVisible(false);
        cc_0.setVisible(false);

    }

    private void visible1() {
        lb_1.setVisible(true);
        cc_1.setVisible(true);

    }

    private void visible2() {
        lb_2.setVisible(true);
        cc_2.setVisible(true);

    }

    private void visible3() {
        lb_3.setVisible(true);
        cc_3.setVisible(true);
    }

    private void visible4() {
        lb_4.setVisible(true);
        cc_4.setVisible(true);

    }

    private void visible5() {
        lb_5.setVisible(true);

        cc_5.setVisible(true);
    }

    private void visible6T() {
        lb_6.setVisible(true);
        cc_6.setVisible(true);
    }

    private void visible6f() {
        lb_6.setVisible(false);
        cc_6.setVisible(false);
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        visibleCC();
        visible6f();
        visible0T();
        type = 2;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cc_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cc_0ActionPerformed
        setIndex();
        switch (cc_0.getSelectedIndex()) {
            case 1:
                visibleCC();
                visible1();
                break;
            case 2:
                visibleCC();
                visible1();
                visible2();
                break;
            case 3:
                visibleCC();
                visible1();
                visible2();
                visible3();
                break;
            case 4:
                visibleCC();
                visible1();
                visible2();
                visible3();
                visible4();
                break;
            case 5:
                visibleCC();
                visible1();
                visible2();
                visible3();
                visible4();
                visible5();
                break;
            default:
                visibleCC();

        }


    }//GEN-LAST:event_cc_0ActionPerformed
    private ArrayList<Integer> popular() {
        ArrayList<Integer> a = new ArrayList<Integer>();

        switch (cc_0.getSelectedIndex()) {
            case 5:
                a.add(cc_5.getSelectedIndex() + 1);
            case 4:
                a.add(cc_4.getSelectedIndex() + 1);
            case 3:
                a.add(cc_3.getSelectedIndex() + 1);
            case 2:
                a.add(cc_2.getSelectedIndex() + 1);
            case 1:
                a.add(cc_1.getSelectedIndex() + 1);
                break;
            default:
                a.add(0);
        }
        return a;
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        JFrame jFrame = new JFrame("Thread");
        switch (type) {
            case 1:
                ArrayList<Integer> a;
                a = new ArrayList<Integer>();

                Animacao modoKernel = new Animacao(cc_0.getSelectedIndex(), popular(), cc_6.getSelectedIndex(), 1);
                jFrame.add(modoKernel);
                jFrame.setLocationRelativeTo(null);
                jFrame.pack();
                jFrame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                jFrame.setVisible(true);
                new Thread(modoKernel).start();
                break;
            case 2:
                Animacao modoUsuario = new Animacao(cc_0.getSelectedIndex(), popular(), cc_6.getSelectedIndex(), 2);

                jFrame.add(modoUsuario);
                jFrame.setLocationRelativeTo(null);
                jFrame.pack();
                jFrame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                jFrame.setVisible(true);

                new Thread(modoUsuario).start();
                break;

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cc_0;
    private javax.swing.JComboBox<String> cc_1;
    private javax.swing.JComboBox<String> cc_2;
    private javax.swing.JComboBox<String> cc_3;
    private javax.swing.JComboBox<String> cc_4;
    private javax.swing.JComboBox<String> cc_5;
    private javax.swing.JComboBox<String> cc_6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_0;
    private javax.swing.JPanel lb_01;
    private javax.swing.JLabel lb_1;
    private javax.swing.JLabel lb_2;
    private javax.swing.JLabel lb_3;
    private javax.swing.JLabel lb_4;
    private javax.swing.JLabel lb_5;
    private javax.swing.JLabel lb_6;
    // End of variables declaration//GEN-END:variables
}
